[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "KDSource"
authors = [{name = "Osiris Inti Abbate", email = "intiabbate@gmail.com"}]
dynamic = ["version", "description"]